### ISSUE TITLE
How can I modify ?

### ISSUE THREAD

**Issue by anis8123** [square/in-app-payments-flutter-plugin#111]
How can I change the index.js file because the amount is fixed and I want it variable

**Comment by StephenJosey** [comment]
If you're solely referring to the Heroku quickstart server, then you need to clone it locally to your computer, change [this line](https://github.com/square/in-app-payments-server-quickstart/blob/master/index.js#L126), and then push it back to Heroku so that it's deployed on your Heroku server.

You can, of course, alternatively set up your own server and edit the files as needed.

**Comment by anis8123** [comment]
I make the modification (amount: requestBody.amount,)
after deployment it remains always 1

**Comment by StephenJosey** [comment]
That's the only place that the amount gets set, so either the changes didn't save or `requestBody.amount` is equal to `100`. Could you try printing something to make sure the changes actually saved and were deployed?

**Comment by anis8123** [comment]
I tried several times the deployment does not apply
You have created my personal server
And thanks for the help(@StephenJosey )

**Comment by StephenJosey** [comment]
Sorry for the delay. I'm not sure what you mean by the deployment does not apply. If you make other changes, does it seem to do anything? You can also create your own server if you're more comfortable with that.

**Comment by StephenJosey** [comment]
Please reopen if you have further information.
