### ISSUE TITLE
androidx

### ISSUE THREAD

**Issue by tegab** [square/in-app-payments-flutter-plugin#23]
please help.. i tried updating to androidx.  i can not seem to get this to work.  i am getting 

.pub-cache/hosted/pub.dartlang.org/square_in_app_payments-1.0.2/android/src/main/java/sqip/flutter/internal/GooglePayModule.java:119: error: cannot find symbol
      public void onComplete(@NonNull Task<Boolean> task) {

**Comment by hukid** [comment]
Hi, @tegab. Thanks for reporting this issue!

It seems in-app payments plugin hasn't been updated to support Androidx yet, and so do many other third party plugins according to this thread: https://github.com/flutter/flutter/issues/23995

While we are working on a solution for you (we are on it now), do you really need to update to androidx at this moment because you may hit same issue for other third party plugins? Or you can wait for a little bit?

I'll see if we can find a workaround for you.

**Comment by tegab** [comment]
i reverted back to old version.

**Comment by hukid** [comment]
There is no good workaround at this stage per flutter team's response.

We'll update the plugin once there is official guideline for AndroidX migration of third party plugins.

closing this issue.

**Comment by hukid** [comment]
@tegab We found the android.support dependency in the plugin is not necessary, PR #26 should enable you to migrate to AndroidX.
