### ISSUE TITLE
[Feature Inquiry] Adding Customers

### ISSUE THREAD

**Issue by DarthWindu** [square/in-app-payments-flutter-plugin#37]
Will this SDK support adding customers? Or is there a separate SDK that provides v2 functionality?

**Comment by StephenJosey** [comment]
Hey @DarthWindu - we actually have several other APIs that can do all sorts of things, creating customers included! We strongly recommend that you have a backend server/service running that will do the API calls, and your mobile application will ping your server/service so that you don't store your access token within your mobile application.

For information on how to create a customer, take a look here: https://docs.connect.squareup.com/api/connect/v2#endpoint-customers-createcustomer

I imagine you're already calling `Charge` if you're using In-App Payments SDK, so you could easily create a customer at the same time, and then pass in the `customer_id` to the `Charge` request so that a customer is added to the transaction. Take a look here: https://docs.connect.squareup.com/payments/transactions/setup#optional-link-a-square-customer-object-id

Please let me know if you have additional questions, though!

**Comment by DarthWindu** [comment]
Thanks Stephen, I appreciate it 👍
