### ISSUE TITLE
Does this plugin support Flutter Desktop apps

### ISSUE THREAD

**Issue by NVivek** [square/in-app-payments-flutter-plugin#53]
Would like to understand if the card readers can be used in a Desktop app and will this plugin support it?

**Comment by havenwood** [comment]
This plugin is for in-app payments from your customer on their device rather than in-person payments using Square hardware. The [Flutter plugin for Reader SDK](https://github.com/square/reader-sdk-flutter-plugin) is for in-person payments, but it is limited to iOS and Android targets.

Please join us in our [Square developer Slack community](http://squ.re/slack) if you'd like to discuss taking payments from a Flutter desktop app. We don't support that out of the box, but might be able to help you come up with something that works for your use case.

**Comment by NVivek** [comment]
Thanks @havenwood
