### ISSUE TITLE
Can't find anywhere about where to put the amount charge in the json.

### ISSUE THREAD

**Issue by mikeyyg96** [square/in-app-payments-flutter-plugin#62]
### Describe your question
This might sound stupid but I am trying to make a specific amount to be charged, but don't know where to put it. My guess is it is in

`var body = jsonEncode({"nonce": result.nonce, "amount": 2, "currency": "USD"});`

but when the transaction occurs, the amount charged is still $1.00. Am I doing something wrong? I am using Heroku as backend.

**Comment by StephenJosey** [comment]
In the Heroku sample server, the amount is being set on the backend (https://github.com/square/in-app-payments-server-quickstart/blob/master/index.js#L43). 

If you're wanting to pass in the value from the front end like your example, you would need to update the above line to just say `amount: requestBody.amount`. Note, though, that the Heroku sample server is simply just creating a basic Cookie item with that amount, so if you're wanting to change items etc you would want to do something more sophisticated on the backend. 

Just changing the amount in your example would thus create a $0.02 cookie (because it's the lowest denomination which is cents) and charge it.

**Comment by mikeyyg96** [comment]
@StephenJosey that link you showed me... is that index.js stored somewhere in my flutter project. If so, where I can modify it to make the changes?

**Comment by havenwood** [comment]
@mikeyyg96 The index.js file is for your backend code rather than the mobile app. There are no dollar amounts in the example Flutter project itself. You can fork the "In-App Payments Server Quickstart" repo that @StephenJosey linked to, change the amount and restart your Heroku dyno for the new price to go live.

Prices are typically set by the backend to avoid folk tampering with amounts. By passing ids for the items being purchased rather than amounts, your backend acts as a pricing point of truth.

**Comment by mikeyyg96** [comment]
@havenwood After forking it and making the change, how will heroku know that I made the change?

**Comment by mikeyyg96** [comment]
I got it working forking the repo and deploying a new heroku app with the repository I forked with the desired change.
