### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by mariapapag95** [square/in-app-payments-flutter-plugin#79]
I would like to see some build in error handling for request errors (like 400 errors) in a similar way the error handling works when the user inputs an invalid card number. It would  be great to not have to manually create UI alerts to the user based on what status code the request body returns.

**Comment by StephenJosey** [comment]
Hi @mariapapag95 - could you elaborate a bit, or help me understand this? The In-App Payments SDK solely is going to attempt to create a nonce for you based on the information you provided and it will provide info if it failed. For charging the card or saving the card on file, you will be using separate APIs (hopefully on a backend server), which should be handling errors such as failed to charge etc.

**Comment by mariapapag95** [comment]
@StephenJosey sure. What I mean is, the plugin has built UI for card entry. It looks and works great. If there is an error with the request to Square's API, it would be great if there was built UI that would relay that error message to the user, rather than us having to build it. For example, an alert that says "There was an error processing your payment" or something like that.

**Comment by StephenJosey** [comment]
Thanks for clarifying! Unfortunately this SDK does not know anything about the requests to other APIs - as I mentioned, that's up to the developer to handle. In the current state, if you used this SDK solely, you wouldn't even be able to charge a card. Thus, there is no way for this SDK to automatically generate an error since all it knows is "did I or did I not create a nonce successfully?".

Also, just to clarify, it does have a pre-built error UI that you are able to use using the [showCardNonceProcessingError](https://github.com/square/in-app-payments-flutter-plugin/blob/master/doc/reference.md#showcardnonceprocessingerror) function while the card entry is still open. So, for example, if you attempted to charge the card on a backend server, and it failed, Square would provide you with a reason (such as "Incorrect CVV"). Then, you can share this info with the user by calling `InAppPayments.showCardNonceProcessingError('Failed to process payment due to incorrect CVV")`.

**Comment by mariapapag95** [comment]
Thanks Stephen!
