### ISSUE TITLE
Nonce generated but not charged

### ISSUE THREAD

**Issue by PramodJoshi** [square/in-app-payments-flutter-plugin#90]
Hi,

I am trying to run square example project with sandbox id and token but i'm getting 'Nonce generated but not charged' error in the app. Tried it with both local server and Heroku, same result. I have chargeServerHost, locationId set in the the project. Any idea why this is happening?

<img width="368" alt="Screen Shot 2020-02-23 at 1 07 39 PM" src="https://user-images.githubusercontent.com/17320471/75118186-8e61f680-563d-11ea-8159-0a818b8d4fe5.png">

**Comment by StephenJosey** [comment]
Hi @PramodJoshi this message is letting you know that you can view the cURL command in the debug logger, so that you can execute it in your own terminal window. If you want to use your own server, you need to replace the `CHARGE_SERVER_HOST` variable within the quickstart. This can be found [here](https://github.com/square/in-app-payments-flutter-plugin/blob/master/example/lib/transaction_service.dart#L24).

**Comment by PramodJoshi** [comment]
@StephenJosey Yes, i'm reloading after saving  :) .  Quick question, i have **config.dart** with sandbox token and location id and **transaction_service.dart** with server host but **buy_sheet.dart** has couple of 'REPLACE_ME' , should these be replaced too (i did, but seems like these are just the checks, kind of confusing with REPLACE_ME text)?

**Comment by StephenJosey** [comment]
The check happens here: https://github.com/square/in-app-payments-flutter-plugin/blob/master/example/lib/widgets/buy_sheet.dart#L176 which relies on the `_chargeServerHostReplaced` variable, which just checks to see if `chargeServerHost` is not equal to `REPLACE_ME`. So this message should only print if `chargeServerHost` is set to `REPLACE_ME`, otherwise it will attempt to call your charge host and provide a different message.

**Comment by PramodJoshi** [comment]
@StephenJosey yup, that was it. Thanks for the prompt response.
